language: ruby
rvm:
  - 2.0.0
services:
  - docker
before_install:
  - git submodule update --init --recursive
  - pip install --user zapcli
before_script:
  - pushd vendor/railsgoat
  - bundle exec rake db:setup
  - bundle exec rails server -d
  - popd
script:
  - docker run -u zap -i owasp/zap2docker-stable zap-cli quick-scan -sc \
    -o '-config api.disablekey=true' -s xss,sqli --spider http://localhost:3000/
